#ifndef LAMPS_H
#define LAMPS_H

#define FLASH_FREQUENCY                 100

#define LAMP_TERMINATOR                 255
#define LAMP_PLAYFIELD_GI               0
#define LAMP_RELEASE_ORB                1
#define LAMP_RIGHT_LANE_RELEASE_ORBS    2
#define LAMP_COLLECT_BONUS_ARROW        3
#define LAMP_1K_BONUS                   4
#define LAMP_2K_BONUS                   5
#define LAMP_3K_BONUS                   6
#define LAMP_4K_BONUS                   7
#define LAMP_5K_BONUS                   8
#define LAMP_6K_BONUS                   9
#define LAMP_7K_BONUS                   10
#define LAMP_8K_BONUS                   11
#define LAMP_9K_BONUS                   12
#define LAMP_10K_BONUS                  13
#define LAMP_CHAMBERS_RELEASE           14
#define LAMP_CHAMBERS_SPECIAL           15
#define LAMP_2X_BONUS                   16
#define LAMP_3X_BONUS                   17
#define LAMP_4X_BONUS                   18
#define LAMP_5X_BONUS                   19
#define LAMP_RIGHT_OUT_ROLLOVER         20
#define LAMP_RIGHT_RETURN_ROLLOVER      21
#define LAMP_LEFT_RETURN_ROLLOVER       22
#define LAMP_LEFT_OUT_ROLLOVER          23
#define LAMP_RIGHT_DROP_TARGET_80_ARROW 24
#define LAMP_RIGHT_DROP_TARGET_40_ARROW 25
#define LAMP_RIGHT_DROP_TARGET_20_ARROW 26
#define LAMP_RIGHT_DROP_TARGET_10_ARROW 27
#define LAMP_S_DROP_TARGET_ARROW        28
#define LAMP_B_DROP_TARGET_ARROW        29
#define LAMP_R_DROP_TARGET_ARROW        30
#define LAMP_O_DROP_TARGET_ARROW        31
#define LAMP_10_CHAMBER                 32
#define LAMP_20_CHAMBER                 33
#define LAMP_30_CHAMBER                 34
#define LAMP_40_CHAMBER                 35
#define LAMP_50_CHAMBER                 36
#define LAMP_20K_BONUS                  37
#define LAMP_40K_BONUS                  38
#define LAMP_60K_BONUS                  39
#define LAMP_1_CAPTIVE_ORBS             44
#define LAMP_2_CAPTIVE_ORBS             45
#define LAMP_3_CAPTIVE_ORBS             46
#define LAMP_4_CAPTIVE_ORBS             47
#define LAMP_ORBS_SPECIAL               52
#define LAMP_ORBS_50K                   53
#define LAMP_RESET_1_THROUGH_4_ARROW    54
#define LAMP_SPOT_1_THROUGH_4           55
#define LAMP_RIGHT_LANE_2X              56
#define LAMP_RIGHT_LANE_3X              57
#define LAMP_RIGHT_LANE_4X              58
#define LAMP_RIGHT_LANE_5X              59
#define LAMP_TOP_RIGHT_ROLLOVER         60
#define LAMP_TOP_MIDDLE_ROLLOVER        61
#define LAMP_TOP_LEFT_ROLLOVER          62
#define LAMP_RIGHT_SLINGSHOT_GI         64
#define LAMP_LEFT_SLINGSHOT_GI          65
#define LAMP_RIGHT_THUMPER_BUMPER       66
#define LAMP_LEFT_THUMPER_BUMPER        67
#define LAMP_QUEENS_CHAMBER_GI_1        68
#define LAMP_QUEENS_CHAMBER_GI_2        69
#define LAMP_QUEENS_CHAMBER_GI_3        70
#define LAMP_QUEENS_CHAMBER_GI_4        71

#define LAMP_COLLECTION_BONUS_ALL                0
#define LAMP_COLLECTION_BONUS_MIDDLE_RING        1
#define LAMP_COLLECTION_BONUS_OUTER_RING         2
#define LAMP_COLLECTION_RING_4                   3
#define LAMP_COLLECTION_RING_5                   4
#define LAMP_COLLECTION_RING_6                   5
#define LAMP_COLLECTION_RING_7                   6
#define LAMP_COLLECTION_RING_8                   7
#define LAMP_COLLECTION_RING_9                   8
#define LAMP_COLLECTION_RING_10                  9
#define LAMP_COLLECTION_RING_11                  10
#define LAMP_COLLECTION_RING_12                  11
#define LAMP_COLLECTION_RING_13                  12
#define LAMP_COLLECTION_RING_14                  13
#define LAMP_COLLECTION_TOP_ROLLOVERS            14
#define LAMP_COLLECTION_ALL_ROLLOVERS            15
#define LAMP_COLLECTION_CAPTIVE_ORBS             16
#define LAMP_COLLECTION_RIGHT_DROP_TARGET_ARROWS 17
#define LAMP_COLLECTION_ORBS_DROP_TARGET_ARROWS  18
#define LAMP_COLLECTION_GENERAL_ILLUMINATION     19
#define LAMP_COLLECTION_QUEENS_CHAMBER_HURRY_UP  20
#define LAMP_COLLECTION_ORB_FEATURE              21
#define LAMP_COLLECTION_SEQUENCE_FEATURE         22
#define LAMP_COLLECTION_CHAMBER_FEATURE          23
#define LAMP_COLLECTION_GUARDIAN_FEATURE         24
#define LAMP_COLLECTION_BONUS_FEATURE            25
#define LAMP_COLLECTION_BONUS_COUNTDOWN_STEP_1   26
#define LAMP_COLLECTION_BONUS_COUNTDOWN_STEP_2   27
#define LAMP_COLLECTION_BONUS_COUNTDOWN_STEP_3   28
#define LAMP_COLLECTION_BONUS_COUNTDOWN_STEP_4   29
#define LAMP_COLLECTION_BONUS_COUNTDOWN_STEP_5   30
#define LAMP_COLLECTION_BONUS_RESET_ARROW        31
#define LAMP_COLLECTION_BONUS_ORBS_DROPS_ARROW   32
#define LAMP_COLLECTION_BONUS_RIGHT_DROPS_ARROW  33
#define LAMP_COLLECTION_QUEENS_CHAMBER_GI        34

static byte bonusAllLamps_[] = {
  LAMP_1K_BONUS,
  LAMP_2K_BONUS,
  LAMP_3K_BONUS,
  LAMP_4K_BONUS,
  LAMP_5K_BONUS,
  LAMP_6K_BONUS,
  LAMP_7K_BONUS,
  LAMP_8K_BONUS,
  LAMP_9K_BONUS,
  LAMP_10K_BONUS,
  LAMP_20K_BONUS,
  LAMP_40K_BONUS,
  LAMP_60K_BONUS,
  LAMP_2X_BONUS,
  LAMP_3X_BONUS,
  LAMP_4X_BONUS,
  LAMP_5X_BONUS,
  LAMP_TERMINATOR
};

static byte bonusMiddleRingLamps_[] = {
  LAMP_20K_BONUS,
  LAMP_60K_BONUS,
  LAMP_2X_BONUS,
  LAMP_3X_BONUS,
  LAMP_4X_BONUS,
  LAMP_5X_BONUS,
  LAMP_TERMINATOR
};

static byte bonusOuterRingLamps_[] = {
  LAMP_1K_BONUS,
  LAMP_2K_BONUS,
  LAMP_3K_BONUS,
  LAMP_4K_BONUS,
  LAMP_5K_BONUS,
  LAMP_6K_BONUS,
  LAMP_7K_BONUS,
  LAMP_8K_BONUS,
  LAMP_9K_BONUS,
  LAMP_10K_BONUS,
  LAMP_TERMINATOR
};

static byte ring4Lamps_[] = {
  LAMP_2_CAPTIVE_ORBS,
  LAMP_3_CAPTIVE_ORBS,
  LAMP_LEFT_RETURN_ROLLOVER,
  LAMP_RIGHT_DROP_TARGET_80_ARROW,
  LAMP_RIGHT_RETURN_ROLLOVER,
  LAMP_TERMINATOR
};

static byte ring5Lamps_[] = {
  LAMP_10_CHAMBER,
  LAMP_1_CAPTIVE_ORBS,
  LAMP_4_CAPTIVE_ORBS,
  LAMP_LEFT_OUT_ROLLOVER,
  LAMP_LEFT_SLINGSHOT_GI,
  LAMP_RIGHT_DROP_TARGET_40_ARROW,
  LAMP_RIGHT_OUT_ROLLOVER,
  LAMP_RIGHT_SLINGSHOT_GI,
  LAMP_TERMINATOR
};

static byte ring6Lamps_[] = {
  LAMP_20_CHAMBER,
  LAMP_RELEASE_ORB,
  LAMP_RESET_1_THROUGH_4_ARROW,
  LAMP_RIGHT_DROP_TARGET_20_ARROW,
  LAMP_TERMINATOR
};

static byte ring7Lamps_[] = {
  LAMP_30_CHAMBER,
  LAMP_ORBS_50K,
  LAMP_ORBS_SPECIAL,
  LAMP_RIGHT_DROP_TARGET_10_ARROW,
  LAMP_TERMINATOR
};

static byte ring8Lamps_[] = {
  LAMP_40_CHAMBER,
  LAMP_B_DROP_TARGET_ARROW,
  LAMP_O_DROP_TARGET_ARROW,
  LAMP_R_DROP_TARGET_ARROW,
  LAMP_S_DROP_TARGET_ARROW,
  LAMP_TERMINATOR
};

static byte ring9Lamps_[] = {
  LAMP_50_CHAMBER,
  LAMP_RIGHT_LANE_RELEASE_ORBS,
  LAMP_TERMINATOR
};

static byte ring10Lamps_[] = {
  LAMP_RIGHT_LANE_2X,
  LAMP_LEFT_THUMPER_BUMPER,
  LAMP_QUEENS_CHAMBER_GI_1,
  LAMP_RIGHT_THUMPER_BUMPER,
  LAMP_TERMINATOR
};

static byte ring11Lamps_[] = {
  LAMP_RIGHT_LANE_3X,
  LAMP_QUEENS_CHAMBER_GI_2,
  LAMP_TERMINATOR
};

static byte ring12Lamps_[] = {
  LAMP_RIGHT_LANE_5X,
  LAMP_QUEENS_CHAMBER_GI_3,
  LAMP_SPOT_1_THROUGH_4,
  LAMP_TERMINATOR
};

static byte ring13Lamps_[] = {
  LAMP_CHAMBERS_SPECIAL,
  LAMP_TOP_LEFT_ROLLOVER,
  LAMP_TOP_MIDDLE_ROLLOVER,
  LAMP_TOP_RIGHT_ROLLOVER,
  LAMP_TERMINATOR
};

static byte ring14Lamps_[] = {
  LAMP_CHAMBERS_RELEASE,
  LAMP_QUEENS_CHAMBER_GI_4,
  LAMP_TERMINATOR
};

static byte topRolloverLamps_[] = {
  LAMP_TOP_LEFT_ROLLOVER,
  LAMP_TOP_MIDDLE_ROLLOVER,
  LAMP_TOP_RIGHT_ROLLOVER,
  LAMP_TERMINATOR
};

static byte allRolloverLamps_[] = {
  LAMP_TOP_LEFT_ROLLOVER,
  LAMP_TOP_MIDDLE_ROLLOVER,
  LAMP_TOP_RIGHT_ROLLOVER,
  LAMP_LEFT_OUT_ROLLOVER,
  LAMP_LEFT_RETURN_ROLLOVER,
  LAMP_RIGHT_RETURN_ROLLOVER,
  LAMP_RIGHT_OUT_ROLLOVER,
  LAMP_TERMINATOR
};

static byte captiveOrbsLamps_[] = {
  LAMP_1_CAPTIVE_ORBS,
  LAMP_2_CAPTIVE_ORBS,
  LAMP_3_CAPTIVE_ORBS,
  LAMP_4_CAPTIVE_ORBS,
  LAMP_TERMINATOR
};

static byte rightDropTargetArrowsLamps_[] = {
  LAMP_RIGHT_DROP_TARGET_10_ARROW,
  LAMP_RIGHT_DROP_TARGET_20_ARROW,
  LAMP_RIGHT_DROP_TARGET_40_ARROW,
  LAMP_RIGHT_DROP_TARGET_80_ARROW,
  LAMP_TERMINATOR
};

static byte orbsDropTargetArrowsLamps_[] = {
  LAMP_O_DROP_TARGET_ARROW,
  LAMP_R_DROP_TARGET_ARROW,
  LAMP_B_DROP_TARGET_ARROW,
  LAMP_S_DROP_TARGET_ARROW,
  LAMP_TERMINATOR
};

static byte queensChamberHurryUpLamps_[] = {
  LAMP_10_CHAMBER,
  LAMP_20_CHAMBER,
  LAMP_30_CHAMBER,
  LAMP_40_CHAMBER,
  LAMP_50_CHAMBER,
  LAMP_TERMINATOR
};

static byte orbFeatureLamps_[] = {
  LAMP_1_CAPTIVE_ORBS,
  LAMP_2_CAPTIVE_ORBS,
  LAMP_3_CAPTIVE_ORBS,
  LAMP_4_CAPTIVE_ORBS,
  LAMP_B_DROP_TARGET_ARROW,
  LAMP_O_DROP_TARGET_ARROW,
  LAMP_R_DROP_TARGET_ARROW,
  LAMP_S_DROP_TARGET_ARROW,
  LAMP_TERMINATOR
};

static byte sequenceFeatureLamps_[] = {
  LAMP_RESET_1_THROUGH_4_ARROW,
  LAMP_RIGHT_DROP_TARGET_10_ARROW,
  LAMP_RIGHT_DROP_TARGET_20_ARROW,
  LAMP_RIGHT_DROP_TARGET_40_ARROW,
  LAMP_RIGHT_DROP_TARGET_80_ARROW,
  LAMP_SPOT_1_THROUGH_4,
  LAMP_TERMINATOR
};

static byte chamberFeatureLamps_[] = {
  LAMP_10_CHAMBER,
  LAMP_20_CHAMBER,
  LAMP_30_CHAMBER,
  LAMP_40_CHAMBER,
  LAMP_50_CHAMBER,
  LAMP_QUEENS_CHAMBER_GI_1,
  LAMP_QUEENS_CHAMBER_GI_2,
  LAMP_QUEENS_CHAMBER_GI_3,
  LAMP_QUEENS_CHAMBER_GI_4,
  LAMP_TERMINATOR
};

static byte guardianFeatureLamps_[] = {
  LAMP_LEFT_OUT_ROLLOVER,
  LAMP_LEFT_RETURN_ROLLOVER,
  LAMP_RELEASE_ORB,
  LAMP_RIGHT_OUT_ROLLOVER,
  LAMP_RIGHT_RETURN_ROLLOVER,
  LAMP_TERMINATOR
};

static byte bonusFeatureLamps_[] = {
  LAMP_1K_BONUS,
  LAMP_2K_BONUS,
  LAMP_3K_BONUS,
  LAMP_4K_BONUS,
  LAMP_5K_BONUS,
  LAMP_6K_BONUS,
  LAMP_7K_BONUS,
  LAMP_8K_BONUS,
  LAMP_9K_BONUS,
  LAMP_10K_BONUS,
  LAMP_20K_BONUS,
  LAMP_40K_BONUS,
  LAMP_60K_BONUS,
  LAMP_2X_BONUS,
  LAMP_3X_BONUS,
  LAMP_4X_BONUS,
  LAMP_5X_BONUS,
  LAMP_TOP_LEFT_ROLLOVER,
  LAMP_TOP_MIDDLE_ROLLOVER,
  LAMP_TOP_RIGHT_ROLLOVER,
  LAMP_TERMINATOR
};

static byte playfieldGeneralIllumination_[] = {
  LAMP_PLAYFIELD_GI,
  LAMP_RIGHT_THUMPER_BUMPER,
  LAMP_LEFT_THUMPER_BUMPER,
  LAMP_QUEENS_CHAMBER_GI_1,
  LAMP_QUEENS_CHAMBER_GI_2,
  LAMP_QUEENS_CHAMBER_GI_3,
  LAMP_QUEENS_CHAMBER_GI_4,
  LAMP_TERMINATOR
};

static byte bonusCountdownStep1_[] = {
  LAMP_1K_BONUS,
  LAMP_20K_BONUS,
  LAMP_40K_BONUS,
  LAMP_60K_BONUS,
  LAMP_6K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusCountdownStep2_[] = {
  LAMP_2K_BONUS,
  LAMP_3X_BONUS,
  LAMP_40K_BONUS,
  LAMP_4X_BONUS,
  LAMP_7K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusCountdownStep3_[] = {
  LAMP_3K_BONUS,
  LAMP_40K_BONUS,
  LAMP_8K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusCountdownStep4_[] = {
  LAMP_4K_BONUS,
  LAMP_5X_BONUS,
  LAMP_40K_BONUS,
  LAMP_2X_BONUS,
  LAMP_9K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusCountdownStep5_[] = {
  LAMP_5K_BONUS,
  LAMP_60K_BONUS,
  LAMP_40K_BONUS,
  LAMP_20K_BONUS,
  LAMP_10K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusResetArrow_[] = {
  LAMP_8K_BONUS,
  LAMP_9K_BONUS,
  LAMP_10K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusOrbsDropsArrow_[] = {
  LAMP_9K_BONUS,
  LAMP_10K_BONUS,
  LAMP_1K_BONUS,
  LAMP_2K_BONUS,
  LAMP_TERMINATOR
};

static byte bonusRightDropsArrow_[] = {
  LAMP_1K_BONUS,
  LAMP_2K_BONUS,
  LAMP_3K_BONUS,
  LAMP_TERMINATOR
};

static byte queensChamberGI_[] = {
  LAMP_QUEENS_CHAMBER_GI_1,
  LAMP_QUEENS_CHAMBER_GI_2,
  LAMP_QUEENS_CHAMBER_GI_3,
  LAMP_QUEENS_CHAMBER_GI_4,
  LAMP_TERMINATOR
};

static byte descendingBonusValues_[] = {
  60,
  40,
  20,
  10,
  9,
  8,
  7,
  6,
  5,
  4,
  3,
  2,
  1
};

static byte descendingBonusLamps_[] = {
  LAMP_60K_BONUS,
  LAMP_40K_BONUS,
  LAMP_20K_BONUS,
  LAMP_10K_BONUS,
  LAMP_9K_BONUS,
  LAMP_8K_BONUS,
  LAMP_7K_BONUS,
  LAMP_6K_BONUS,
  LAMP_5K_BONUS,
  LAMP_4K_BONUS,
  LAMP_3K_BONUS,
  LAMP_2K_BONUS,
  LAMP_1K_BONUS
};

class LampsHelper {
  private:
    byte* lampsPointer(byte lampCollection);

  public:
    LampsHelper();

    void hideAllLamps();
    void hideLamp(byte lamp);
    void hideLamps(byte lampCollection);
    void showAllLamps();
    void showBonusLamps(byte value);
    void showBonusMultiplierLamps(byte value);
    void showLamp(byte lamp, bool flash = false);
    void showLamps(byte lampCollection, bool flash = false);
};

#endif
