#define LAMP_TERMINATOR                 -1
#define LAMP_PLAYFIELD_GI               0
#define LAMP_RIGHT_LANE_RELEASE_ORBS    2
#define LAMP_COLLECT_BONUS_ARROW        3
#define LAMP_1K_BONUS                   4
#define LAMP_2K_BONUS                   5
#define LAMP_3K_BONUS                   6
#define LAMP_4K_BONUS                   7
#define LAMP_5K_BONUS                   8
#define LAMP_6K_BONUS                   9
#define LAMP_7K_BONUS                   10
#define LAMP_8K_BONUS                   11
#define LAMP_9K_BONUS                   12
#define LAMP_10K_BONUS                  13
#define LAMP_CHAMBERS_RELEASE           14
#define LAMP_CHAMBERS_SPECIAL           15
#define LAMP_2X_BONUS                   16
#define LAMP_3X_BONUS                   17
#define LAMP_4X_BONUS                   18
#define LAMP_5X_BONUS                   19
#define LAMP_RIGHT_OUT_ROLLOVER         20
#define LAMP_RIGHT_RETURN_ROLLOVER      21
#define LAMP_LEFT_RETURN_ROLLOVER       22
#define LAMP_LEFT_OUT_ROLLOVER          23
#define LAMP_RIGHT_DROP_TARGET_80_ARROW 24
#define LAMP_RIGHT_DROP_TARGET_40_ARROW 25
#define LAMP_RIGHT_DROP_TARGET_20_ARROW 26
#define LAMP_RIGHT_DROP_TARGET_10_ARROW 27
#define LAMP_S_DROP_TARGET_ARROW        28
#define LAMP_B_DROP_TARGET_ARROW        28
#define LAMP_R_DROP_TARGET_ARROW        28
#define LAMP_O_DROP_TARGET_ARROW        28
#define LAMP_10_CHAMBER                 32
#define LAMP_20_CHAMBER                 33
#define LAMP_30_CHAMBER                 34
#define LAMP_40_CHAMBER                 35
#define LAMP_50_CHAMBER                 36
#define LAMP_20K_BONUS                  37
#define LAMP_40K_BONUS                  38
#define LAMP_60K_BONUS                  39
#define LAMP_SHOOT_AGAIN                40
#define LAMP_MATCH                      41
#define LAMP_WARNING                    42
#define LAMP_CREDIT_INDICATOR           43
#define LAMP_1_CAPTIVE_ORBS             44
#define LAMP_2_CAPTIVE_ORBS             45
#define LAMP_3_CAPTIVE_ORBS             46
#define LAMP_4_CAPTIVE_ORBS             47
#define LAMP_BALL_IN_PLAY               48
#define LAMP_HIGH_SCORE_TO_DATE         49
#define LAMP_GAME_OVER                  50
#define LAMP_TILT                       51
#define LAMP_ORBS_SPECIAL               52
#define LAMP_ORBS_50K                   53
#define LAMP_RESET_1_THROUGH_4_ARROW    54
#define LAMP_SPOT_1_THROUGH_4           55
#define LAMP_RIGHT_LANE_2X              56
#define LAMP_RIGHT_LANE_3X              57
#define LAMP_RIGHT_LANE_4X              58
#define LAMP_RIGHT_LANE_5X              59
#define LAMP_TOP_RIGHT_ROLLOVER         60
#define LAMP_TOP_MIDDLE_ROLLOVER        61
#define LAMP_TOP_LEFT_ROLLOVER          62
#define LAMP_RIGHT_SLINGSHOT_GI         64
#define LAMP_LEFT_SLINGSHOT_GI          65
#define LAMP_RIGHT_THUMPER_BUMPER       66
#define LAMP_LEFT_THUMPER_BUMPER        67
#define LAMP_QUEENS_CHAMBER_GI_1        68
#define LAMP_QUEENS_CHAMBER_GI_2        69
#define LAMP_QUEENS_CHAMBER_GI_3        70
#define LAMP_QUEENS_CHAMBER_GI_4        71

#define SW_4TH_BALL_TROUGH                    0
#define SW_5TH_BALL_TROUGH                    1
#define SW_TOP_RIGHT_LANE                     2
#define SW_TOP_MIDDLE_LANE                    3
#define SW_TOP_LEFT_LANE                      4
#define SW_CREDIT_BUTTON                      5
#define SW_OUTHOLE                            7
#define SW_COIN_3                             8
#define SW_COIN_1                             9
#define SW_COIN_2                             10
#define SW_TOP_LEFT_LANE_RO_BUTTON            11
#define SW_ORBS_2_BACK_TARGETS                11
#define SW_TARGET_BEHIND_RIGHT_THUMPER_BUMPER 11
#define SW_TILT                               14
#define SW_SLAM                               15
#define SW_1ST_BALL_TROUGH                    16
#define SW_LEFT_SIDE_RO_BUTTON                17
#define SW_ORBS_RIGHT_LANE_TARGET             18
#define SW_INLANE_BACK_TARGET                 19
#define SW_LEFT_FLIPPER_BUTTON                20
#define SW_RIGHT_FLIPPER_BUTTON               20
#define SW_RESET_1_THROUGH_4_TARGETS_TARGET   21
#define SW_TOP_STOP_1_THROUGH_4_TARGET        23
#define SW_RIGHT_4_DROP_TARGET_4              24
#define SW_RIGHT_4_DROP_TARGET_3              25
#define SW_RIGHT_4_DROP_TARGET_2              26
#define SW_RIGHT_4_DROP_TARGET_1              27
#define SW_S_DROP_TARGET                      28
#define SW_B_DROP_TARGET                      29
#define SW_R_DROP_TARGET                      30
#define SW_O_DROP_TARGET                      31
#define SW_END_OF_TROUGH                      32
#define SW_10_POINT_REBOUND                   33
#define SW_RIGHT_SLINGSHOT                    36
#define SW_LEFT_SLINGSHOT                     37
#define SW_RIGHT_THUMPER_BUMPER               38
#define SW_LEFT_THUMPER_BUMPER                39
#define SW_1ST_INLINE_DROP_TARGET             40
#define SW_2ND_INLINE_DROP_TARGET             41
#define SW_3RD_INLINE_DROP_TARGET             42
#define SW_4TH_INLINE_DROP_TARGET             43
#define SW_RIGHT_OUTLANE                      44
#define SW_RIGHT_RETURN_LANE                  45
#define SW_LEFT_RETURN_LANE                   46
#define SW_LEFT_OUTLANE                       47

#define SOL_ORBS_TARGET_RESET         0
#define SOL_RIGHT_4_DROP_TARGETS_1    1
#define SOL_RIGHT_4_DROP_TARGETS_2    2
#define SOL_RIGHT_4_DROP_TARGETS_3    3
#define SOL_RIGHT_4_DROP_TARGETS_4    4
#define SOL_KNOCKER                   5
#define SOL_OUTHOLE_KICKER            6
#define SOL_INLINE_DROP_TARGET_RESET  7
#define SOL_4_RIGHT_DROP_TARGET_RESET 8
#define SOL_LEFT_THUMPER_BUMPER       9
#define SOL_RIGHT_THUMPER_BUMPER      10
#define SOL_LEFT_SLINGSHOT            11
#define SOL_RIGHT_SLINGSHOT           12
#define SOL_BALL_KICK_TO_PLAYFIELD    13
#define SOL_BALL_RELEASE              14
#define SOL_COIN_LOCKOUT_DOOR         15
#define SOL_K1_RELAY                  16
#define SOL_MAGNET                    17

#define NUM_SWITCHES_WITH_TRIGGERS          4
#define NUM_PRIORITY_SWITCHES_WITH_TRIGGERS 4
