#define SW_4TH_BALL_TROUGH                    0
#define SW_5TH_BALL_TROUGH                    1
#define SW_TOP_RIGHT_LANE                     2
#define SW_TOP_MIDDLE_LANE                    3
#define SW_TOP_LEFT_LANE                      4
#define SW_CREDIT_BUTTON                      5
#define SW_OUTHOLE                            7
#define SW_COIN_3                             8
#define SW_COIN_1                             9
#define SW_COIN_2                             10
#define SW_TOP_LEFT_LANE_RO_BUTTON            11
#define SW_ORBS_2_BACK_TARGETS                11
#define SW_TARGET_BEHIND_RIGHT_THUMPER_BUMPER 11
#define SW_TILT                               14
#define SW_SLAM                               15
#define SW_1ST_BALL_TROUGH                    16
#define SW_LEFT_SIDE_RO_BUTTON                17
#define SW_ORBS_RIGHT_LANE_TARGET             18
#define SW_INLINE_BACK_TARGET                 19
#define SW_LEFT_FLIPPER_BUTTON                20
#define SW_RIGHT_FLIPPER_BUTTON               20
#define SW_RESET_1_THROUGH_4_TARGETS_TARGET   21
#define SW_TOP_SPOT_1_THROUGH_4_TARGET        23
#define SW_RIGHT_4_DROP_TARGET_4              24
#define SW_RIGHT_4_DROP_TARGET_3              25
#define SW_RIGHT_4_DROP_TARGET_2              26
#define SW_RIGHT_4_DROP_TARGET_1              27
#define SW_S_DROP_TARGET                      28
#define SW_B_DROP_TARGET                      29
#define SW_R_DROP_TARGET                      30
#define SW_O_DROP_TARGET                      31
#define SW_END_OF_TROUGH                      32
#define SW_10_POINT_REBOUND                   33
#define SW_RIGHT_SLINGSHOT                    36
#define SW_LEFT_SLINGSHOT                     37
#define SW_RIGHT_THUMPER_BUMPER               38
#define SW_LEFT_THUMPER_BUMPER                39
#define SW_1ST_INLINE_DROP_TARGET             40
#define SW_2ND_INLINE_DROP_TARGET             41
#define SW_3RD_INLINE_DROP_TARGET             42
#define SW_4TH_INLINE_DROP_TARGET             43
#define SW_RIGHT_OUTLANE                      44
#define SW_RIGHT_RETURN_LANE                  45
#define SW_LEFT_RETURN_LANE                   46
#define SW_LEFT_OUTLANE                       47

#define SOL_ORBS_TARGET_RESET         0
#define SOL_RIGHT_4_DROP_TARGETS_1    1
#define SOL_RIGHT_4_DROP_TARGETS_2    2
#define SOL_RIGHT_4_DROP_TARGETS_3    3
#define SOL_RIGHT_4_DROP_TARGETS_4    4
#define SOL_KNOCKER                   5
#define SOL_OUTHOLE_KICKER            6
#define SOL_INLINE_DROP_TARGET_RESET  7
#define SOL_4_RIGHT_DROP_TARGET_RESET 8
#define SOL_LEFT_THUMPER_BUMPER       9
#define SOL_RIGHT_THUMPER_BUMPER      10
#define SOL_LEFT_SLINGSHOT            11
#define SOL_RIGHT_SLINGSHOT           12
#define SOL_BALL_KICK_TO_PLAYFIELD    13
#define SOL_BALL_RELEASE              14
#define SOL_COIN_LOCKOUT_DOOR         15
#define SOL_K1_RELAY                  16
#define SOL_MAGNET                    17

#define SOL_BALL_KICK_TO_PLAYFIELD_STRENGTH 7
#define SOL_BALL_RELEASE_STRENGTH           4
#define SOL_INLINE_DROPS_RESET_STRENGTH     6
#define SOL_KNOCKER_STRENGTH                3
#define SOL_ORBS_DROPS_RESET_STRENGTH       6
#define SOL_OUTHOLE_KICKER_STRENGTH         4
#define SOL_PLAYFIELD_KICKER_STRENGTH       4
#define SOL_RIGHT_DROPS_RESET_STRENGTH      6
#define SOL_SINGLE_DROP_STRENGTH            4
#define SOL_SLINGSHOT_STRENGTH              4
#define SOL_THUMPER_BUMPER_STRENGTH         3

#define NUM_SWITCHES_WITH_TRIGGERS          4
#define NUM_PRIORITY_SWITCHES_WITH_TRIGGERS 4
